[project]
name = "gradr"
version = "0.1.0"
description = "Manage grading projects and tasks with ease from the terminal."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=25.1.0",
    "aiosqlite>=0.22.1",
    "sqlalchemy>=2.0.46",
    "textual>=7.4.0",
]
